services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - book-app

  server:
    build: 
      context: ./server
    ports:
      - "30081:30081"
    networks:
      - book-app

networks:
  book-app:
