apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: jyotiraditya11/frontend-book-app:v1
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: book-app
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30080

