apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: jyotiraditya11/backend-book-app:v1
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"

---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: book-app
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30081
  type: NodePort

